name: Deploy TODO App

env:
  S3_BUCKET_NAME: gdsc-nits-ci-demo
  AWS_REGION: ap-south-1

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Dependencies
        run: npm install

      - name: Create Build
        run: npm run build

      - name: Deploy to S3
        run: aws s3 sync ./build/ s3://${{ env.S3_BUCKET_NAME }}
